using System;
using System.Collections.Generic;
using DG.Tweening;
using Logic.Scripts.GameDomain.MVC.Shared;
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using Logic.Scripts.GameDomain.Services.Skills;
using Logic.Scripts.GameDomain.MVC.ExplorationLoadout;
using UnityEngine.EventSystems;

public class ExplorationLoadoutUIView : MonoBehaviour, IExplorationLoadoutView
{
    [Header("Root")]
    [SerializeField] private GameObject _rootPanel;
    [SerializeField] private Button _closeButton;
    [SerializeField] private bool _autoGenerateDebugCanvas;

    [Header("Loadout Slots")]
    [Tooltip("Container da Erza — 4 SkillFrames são gerados aqui ao abrir o painel.")]
    [SerializeField] private Transform _playerSlotsContainer;
    [Tooltip("Container do livro — 4 SkillFrames são gerados aqui ao abrir o painel.")]
    [SerializeField] private Transform _bookSlotsContainer;

    [Header("Catalog")]
    [Tooltip("Parent transform where skill frames are spawned (Grid/Layout group in your scene).")]
    [SerializeField] private Transform _catalogContainer;
    [Tooltip("SkillFrame.prefab — must include LoadoutSkillFrameView.")]
    [SerializeField] private LoadoutSkillFrameView _skillFramePrefab;
    [Tooltip("Opcional. ScrollRect pai do catálogo — desactivado durante drag.")]
    [SerializeField] private ScrollRect _catalogScrollRect;
    [SerializeField] private float _invalidSlotAlpha = 0.35f;
    [SerializeField] private float _dragGhostAlpha = 0.55f;
    [Tooltip("Opcional. Dropdown TMP no prefab da cena (mesma ordem que ExplorationLoadoutSkillFilter).")]
    [SerializeField] private TMP_Dropdown _skillCategoryDropdown;
    [Tooltip("Opcional. Dropdown TMP para filtrar por divindade.")]
    [SerializeField] private TMP_Dropdown _divinityCategoryDropdown;

    [Header("Details")]
    [SerializeField] private TMP_Text _detailNameText;
    [SerializeField] private TMP_Text _detailDivinityText;
    [SerializeField] private TMP_Text _detailSkillTypeText;
    [SerializeField] private TMP_Text _detailDescriptionText;
    [SerializeField] private TMP_Text _detailPowerText;
    [SerializeField] private TMP_Text _detailCostText;
    [SerializeField] private TMP_Text _detailRangeText;
    [SerializeField] private Image _detailBackgroundImage;
    [SerializeField] private Image _detailFrameImage;
    [SerializeField] private Image _detailIconImage;

    private ISkillVisualCatalog _visualCatalog;
    private Action<ExplorationLoadoutSkillFilter> _onCatalogFilterChanged;
    private Action<ExplorationLoadoutDivinityFilter> _onDivinityFilterChanged;
    private Action<SkillDataSO> _onCatalogPreview;
    private Action<SkillDataSO> _onDragBegin;
    private Action<Vector2> _onDragMove;
    private Action _onDragEnd;
    private Action<SkillLoadoutUnitType, int, SkillDataSO> _onSkillDropped;
    private Action<SkillLoadoutUnitType, int> _onEquippedSlotClicked;
    private readonly List<LoadoutSkillFrameView> _catalogItems = new List<LoadoutSkillFrameView>(16);
    private readonly List<LoadoutSkillFrameView> _playerSlotFrames = new List<LoadoutSkillFrameView>(4);
    private readonly List<LoadoutSkillFrameView> _bookSlotFrames = new List<LoadoutSkillFrameView>(4);
    private readonly List<CanvasGroup> _playerSlotCanvasGroups = new List<CanvasGroup>(4);
    private readonly List<CanvasGroup> _bookSlotCanvasGroups = new List<CanvasGroup>(4);
    private LoadoutSkillFrameView _dragGhostFrame;
    private Canvas _rootCanvas;
    private RectTransform _dragGhostParent;

    private void Awake()
    {
        if (_autoGenerateDebugCanvas)
            BuildDebugCanvasIfNeeded();
        EnsureHiddenOnSceneLoad();
    }

    private void EnsureHiddenOnSceneLoad()
    {
        SetVisible(false);
    }

    public bool IsVisible => _rootPanel != null && _rootPanel.activeSelf;

    public void Init(ISkillVisualCatalog visualCatalog = null)
    {
        _visualCatalog = visualCatalog;
        ResolveCanvasReferences();
        SetVisible(false);
    }

    public void RegisterCallbacks(Action onClose,
        Action<ExplorationLoadoutSkillFilter> onCatalogFilterChanged = null,
        Action<ExplorationLoadoutDivinityFilter> onDivinityFilterChanged = null)
    {
        if (_closeButton != null)
        {
            _closeButton.onClick.RemoveAllListeners();
            _closeButton.onClick.AddListener(() => onClose?.Invoke());
        }

        _onCatalogFilterChanged = onCatalogFilterChanged;
        _onDivinityFilterChanged = onDivinityFilterChanged;
        WireSkillCategoryDropdown();
        WireDivinityCategoryDropdown();
    }

    public void RegisterDragCallbacks(
        Action<SkillDataSO> onCatalogPreview,
        Action<SkillDataSO> onDragBegin,
        Action<Vector2> onDragMove,
        Action onDragEnd,
        Action<SkillLoadoutUnitType, int, SkillDataSO> onSkillDropped,
        Action<SkillLoadoutUnitType, int> onEquippedSlotClicked)
    {
        _onCatalogPreview = onCatalogPreview;
        _onDragBegin = onDragBegin;
        _onDragMove = onDragMove;
        _onDragEnd = onDragEnd;
        _onSkillDropped = onSkillDropped;
        _onEquippedSlotClicked = onEquippedSlotClicked;
    }

    void ResolveCanvasReferences()
    {
        if (_rootCanvas == null)
            _rootCanvas = GetComponentInParent<Canvas>();
        if (_dragGhostParent == null)
        {
            if (_rootCanvas != null)
                _dragGhostParent = _rootCanvas.transform as RectTransform;
            else if (_rootPanel != null)
                _dragGhostParent = _rootPanel.transform as RectTransform;
        }
        if (_catalogScrollRect == null && _catalogContainer != null)
            _catalogScrollRect = _catalogContainer.GetComponentInParent<ScrollRect>();
    }

    private void WireSkillCategoryDropdown()
    {
        if (_skillCategoryDropdown == null) return;
        _skillCategoryDropdown.onValueChanged.RemoveListener(OnSkillCategoryDropdownValueChanged);
        _skillCategoryDropdown.ClearOptions();
        var opts = new List<string>(5);
        for (int i = 0; i <= (int)ExplorationLoadoutSkillFilter.Buff; i++)
            opts.Add(ExplorationLoadoutSkillFilterUtil.DisplayLabel((ExplorationLoadoutSkillFilter)i));
        _skillCategoryDropdown.AddOptions(opts);
        _skillCategoryDropdown.SetValueWithoutNotify(0);
        _skillCategoryDropdown.onValueChanged.AddListener(OnSkillCategoryDropdownValueChanged);
    }

    private void OnSkillCategoryDropdownValueChanged(int index)
    {
        if (index < 0 || index > (int)ExplorationLoadoutSkillFilter.Buff) return;
        _onCatalogFilterChanged?.Invoke((ExplorationLoadoutSkillFilter)index);
    }

    private void WireDivinityCategoryDropdown()
    {
        if (_divinityCategoryDropdown == null) return;
        _divinityCategoryDropdown.onValueChanged.RemoveListener(OnDivinityCategoryDropdownValueChanged);
        _divinityCategoryDropdown.ClearOptions();
        var opts = new List<string>(6);
        for (int i = 0; i <= (int)ExplorationLoadoutDivinityFilter.Iara; i++)
            opts.Add(ExplorationLoadoutDivinityFilterUtil.DisplayLabel((ExplorationLoadoutDivinityFilter)i));
        _divinityCategoryDropdown.AddOptions(opts);
        _divinityCategoryDropdown.SetValueWithoutNotify(0);
        _divinityCategoryDropdown.onValueChanged.AddListener(OnDivinityCategoryDropdownValueChanged);
    }

    private void OnDivinityCategoryDropdownValueChanged(int index)
    {
        if (index < 0 || index > (int)ExplorationLoadoutDivinityFilter.Iara) return;
        _onDivinityFilterChanged?.Invoke((ExplorationLoadoutDivinityFilter)index);
    }

    public void SetVisible(bool visible)
    {
        if (_rootPanel != null) _rootPanel.SetActive(visible);
    }

    public void RebuildLoadoutSlots(int slotCount, Func<SkillLoadoutUnitType, int, SkillDataSO> getSkillForSlot)
    {
        RebuildUnitLoadoutSlots(SkillLoadoutUnitType.Player, _playerSlotsContainer, _playerSlotFrames,
            _playerSlotCanvasGroups, slotCount, getSkillForSlot);
        RebuildUnitLoadoutSlots(SkillLoadoutUnitType.Book, _bookSlotsContainer, _bookSlotFrames,
            _bookSlotCanvasGroups, slotCount, getSkillForSlot);
        FinalizeLoadoutSlotLayout(_playerSlotsContainer);
        FinalizeLoadoutSlotLayout(_bookSlotsContainer);
    }

    void RebuildUnitLoadoutSlots(
        SkillLoadoutUnitType unitType,
        Transform container,
        List<LoadoutSkillFrameView> frameList,
        List<CanvasGroup> canvasGroups,
        int slotCount,
        Func<SkillLoadoutUnitType, int, SkillDataSO> getSkillForSlot)
    {
        frameList.Clear();
        canvasGroups.Clear();
        if (container == null || _skillFramePrefab == null || slotCount <= 0) return;

        for (int i = container.childCount - 1; i >= 0; i--)
            Destroy(container.GetChild(i).gameObject);

        for (int i = 0; i < slotCount; i++)
        {
            int slotIndex = i;
            SkillDataSO skill = getSkillForSlot?.Invoke(unitType, slotIndex);
            LoadoutSkillFrameView frame = Instantiate(_skillFramePrefab, container);
            frameList.Add(frame);
            frame.Bind(skill, _visualCatalog, null, null, SkillFrameVisualMode.FullLayers);
            frame.ConfigureAsSlotDropSurface();
            WireSlotDropTarget(frame, unitType, slotIndex);
            canvasGroups.Add(frame.GetOrAddCanvasGroup());
        }
    }

    void WireSlotDropTarget(LoadoutSkillFrameView frame, SkillLoadoutUnitType unitType, int slotIndex)
    {
        if (frame == null) return;

        // IDropHandler requires a Graphic on the same GameObject (img_Paint covers the slot hit area).
        Transform dropSurface = FindDropSurfaceTransform(frame.transform);
        if (dropSurface == null) return;

        var existing = dropSurface.GetComponent<LoadoutSlotDropTarget>();
        if (existing != null) Destroy(existing);

        var dropTarget = dropSurface.gameObject.AddComponent<LoadoutSlotDropTarget>();
        dropTarget.Configure(unitType, slotIndex, _onSkillDropped, _onEquippedSlotClicked);
    }

    static Transform FindDropSurfaceTransform(Transform frameRoot)
    {
        Transform shape = FindNamedChild(frameRoot, "img_Shape");
        if (shape != null) return shape;

        Transform paint = FindNamedChild(frameRoot, "img_Paint");
        if (paint != null) return paint;

        Image anyGraphic = frameRoot.GetComponentInChildren<Image>(true);
        return anyGraphic != null ? anyGraphic.transform : frameRoot;
    }

    static Transform FindNamedChild(Transform root, string childName)
    {
        Transform direct = root.Find(childName);
        if (direct != null) return direct;

        foreach (Transform child in root.GetComponentsInChildren<Transform>(true))
        {
            if (child.name == childName) return child;
        }

        return null;
    }

    static void FinalizeLoadoutSlotLayout(Transform container)
    {
        if (container is not RectTransform rt) return;
        LayoutRebuilder.ForceRebuildLayoutImmediate(rt);
    }

    public void PlayInvalidAssignFeedback(SkillLoadoutUnitType unitType, int slotIndex)
    {
        LoadoutSkillFrameView frame = GetLoadoutSlotFrame(unitType, slotIndex);
        if (frame != null)
            frame.PlayInvalidAssignShake();

        ShakeScreen();
    }

    void ShakeScreen()
    {
        if (_rootPanel == null) return;
        var rootRect = _rootPanel.GetComponent<RectTransform>();
        if (rootRect == null) return;
        DOTween.Kill(rootRect, true);
        rootRect.DOShakeAnchorPos(0.28f, strength: 8f, vibrato: 10, randomness: 35f, fadeOut: true);
    }

    LoadoutSkillFrameView GetLoadoutSlotFrame(SkillLoadoutUnitType unitType, int slotIndex)
    {
        List<LoadoutSkillFrameView> frames = unitType == SkillLoadoutUnitType.Book ? _bookSlotFrames : _playerSlotFrames;
        if (slotIndex < 0 || slotIndex >= frames.Count) return null;
        return frames[slotIndex];
    }

    public void ClearCatalog()
    {
        _catalogItems.Clear();
        if (_catalogContainer == null) return;
        for (int i = _catalogContainer.childCount - 1; i >= 0; i--)
            Destroy(_catalogContainer.GetChild(i).gameObject);
    }

    public LoadoutSkillFrameView CreateCatalogItem(SkillDataSO skill, Action<SkillDataSO> onCatalogClicked)
    {
        if (_catalogContainer == null || _skillFramePrefab == null) return null;
        ResolveCanvasReferences();

        LoadoutSkillFrameView frame = Instantiate(_skillFramePrefab, _catalogContainer);
        _catalogItems.Add(frame);
        frame.Bind(skill, _visualCatalog, onCatalogClicked, null, SkillFrameVisualMode.FrameAndIconOnly);

        GameObject dragHost = frame.GetComponentInChildren<Button>(true) != null
            ? frame.GetComponentInChildren<Button>(true).gameObject
            : frame.gameObject;
        var dragSource = dragHost.GetComponent<LoadoutCatalogSkillDragSource>()
            ?? dragHost.AddComponent<LoadoutCatalogSkillDragSource>();
        dragSource.Configure(
            frame,
            _onCatalogPreview,
            _onDragBegin,
            _onDragMove,
            _onDragEnd,
            _catalogScrollRect);

        return frame;
    }

    public void SetSelectedCatalogSkill(SkillDataSO skill)
    {
        for (int i = 0; i < _catalogItems.Count; i++)
        {
            LoadoutSkillFrameView frame = _catalogItems[i];
            if (frame == null) continue;
            frame.SetCatalogSelected(frame.BoundSkill == skill);
        }
    }

    public void FinalizeCatalogScroll()
    {
        if (_catalogContainer is not RectTransform rt) return;
        LayoutRebuilder.ForceRebuildLayoutImmediate(rt);
        Canvas.ForceUpdateCanvases();
    }

    public void ShowDragGhost(SkillDataSO skill)
    {
        if (skill == null || _skillFramePrefab == null) return;
        ResolveCanvasReferences();
        HideDragGhost();

        Transform parent = _dragGhostParent != null ? _dragGhostParent : transform;
        _dragGhostFrame = Instantiate(_skillFramePrefab, parent);
        _dragGhostFrame.transform.SetAsLastSibling();
        PrepareGhostForDrag(_dragGhostFrame);
        _dragGhostFrame.Bind(skill, _visualCatalog, null, null, SkillFrameVisualMode.FrameAndIconOnly);
        _dragGhostFrame.DisableRaycastTargetsForGhost();
        _dragGhostFrame.SetBlocksRaycasts(false);

        var ghostGroup = _dragGhostFrame.GetOrAddCanvasGroup();
        ghostGroup.alpha = _dragGhostAlpha;
        ghostGroup.blocksRaycasts = false;

        UpdateDragGhostScreenPosition(Input.mousePosition);
    }

    static void PrepareGhostForDrag(LoadoutSkillFrameView ghost)
    {
        if (ghost == null) return;

        // SkillFrame.prefab ships with a nested Canvas — breaks cursor positioning when reparented.
        // Remove dependents before Canvas (Unity blocks Canvas removal while Scaler/Raycaster exist).
        var raycaster = ghost.GetComponent<GraphicRaycaster>();
        if (raycaster != null) Destroy(raycaster);
        var scaler = ghost.GetComponent<CanvasScaler>();
        if (scaler != null) Destroy(scaler);
        var nestedCanvas = ghost.GetComponent<Canvas>();
        if (nestedCanvas != null) Destroy(nestedCanvas);

        if (ghost.transform is not RectTransform rt) return;

        rt.localScale = Vector3.one;
        rt.anchorMin = new Vector2(0.5f, 0.5f);
        rt.anchorMax = new Vector2(0.5f, 0.5f);
        rt.pivot = new Vector2(0.5f, 0.5f);
        rt.sizeDelta = new Vector2(120f, 120f);
        rt.anchoredPosition = Vector2.zero;
    }

    public void UpdateDragGhostScreenPosition(Vector2 screenPosition)
    {
        if (_dragGhostFrame == null) return;

        ResolveCanvasReferences();
        RectTransform parentRect = _dragGhostParent;
        if (parentRect == null && _rootCanvas != null)
            parentRect = _rootCanvas.transform as RectTransform;
        if (parentRect == null || _dragGhostFrame.transform is not RectTransform ghostRect) return;

        Camera eventCamera = _rootCanvas != null && _rootCanvas.renderMode != RenderMode.ScreenSpaceOverlay
            ? _rootCanvas.worldCamera
            : null;

        if (RectTransformUtility.ScreenPointToLocalPointInRectangle(
                parentRect, screenPosition, eventCamera, out Vector2 localPoint))
        {
            ghostRect.anchoredPosition = localPoint;
        }
    }

    public void HideDragGhost()
    {
        if (_dragGhostFrame == null) return;
        Destroy(_dragGhostFrame.gameObject);
        _dragGhostFrame = null;
    }

    public void SetSlotDropHighlight(SkillLoadoutUnitType unitType, int slotIndex, bool canDrop)
    {
        CanvasGroup group = GetSlotCanvasGroup(unitType, slotIndex);
        if (group == null) return;
        group.alpha = canDrop ? 1f : _invalidSlotAlpha;
    }

    public void ClearAllSlotDropHighlights()
    {
        ResetSlotGroupAlphas(_playerSlotCanvasGroups);
        ResetSlotGroupAlphas(_bookSlotCanvasGroups);
    }

    static void ResetSlotGroupAlphas(List<CanvasGroup> groups)
    {
        if (groups == null) return;
        for (int i = 0; i < groups.Count; i++)
        {
            if (groups[i] != null)
                groups[i].alpha = 1f;
        }
    }

    CanvasGroup GetSlotCanvasGroup(SkillLoadoutUnitType unitType, int slotIndex)
    {
        List<CanvasGroup> groups = unitType == SkillLoadoutUnitType.Book ? _bookSlotCanvasGroups : _playerSlotCanvasGroups;
        if (slotIndex < 0 || slotIndex >= groups.Count) return null;
        return groups[slotIndex];
    }

    public void ShowSkillDetails(SkillDataSO skill)
    {
        if (_detailNameText != null) _detailNameText.SetText(skill != null ? skill.SkillName : "-");
        if (_detailDivinityText != null)
            _detailDivinityText.SetText(skill != null ? SkillDivinityUtil.DisplayLabel(skill.Divinity) : "-");
        if (_detailSkillTypeText != null)
            _detailSkillTypeText.SetText(skill != null ? ExplorationLoadoutSkillFilterUtil.DisplayLabel(skill.SkillType) : "-");
        if (_detailDescriptionText != null) _detailDescriptionText.SetText(skill != null ? skill.Description : string.Empty);
        if (_detailPowerText != null) _detailPowerText.SetText(skill != null ? skill.Power.ToString() : "-");
        if (_detailCostText != null)
        {
            if (skill == null) _detailCostText.SetText("-");
            else if (skill.SkillType == SkillType.Passive) _detailCostText.SetText("-");
            else _detailCostText.SetText(skill.Cost.ToString());
        }
        if (_detailRangeText != null)
        {
            if (skill == null) _detailRangeText.SetText("-");
            else if (skill.SkillType == SkillType.SelfBuff) _detailRangeText.SetText("-");
            else _detailRangeText.SetText(skill.Range.ToString("0.##"));
        }
        ApplyDetailVisualLayers(skill);
    }

    private void ApplyDetailVisualLayers(SkillDataSO skill)
    {
        var layout = new SkillSlotVisualApplicator.IconLayoutOptions { PreserveAspect = true };
        SkillSlotVisualApplicator.Apply(
            skill,
            _visualCatalog,
            SkillFrameVisualMode.FullLayers,
            _detailBackgroundImage,
            _detailFrameImage,
            _detailIconImage,
            layout);
    }

    private static void AddPanelOutline(GameObject go, Color outlineColor)
    {
        var o = go.AddComponent<Outline>();
        o.effectColor = outlineColor;
        o.effectDistance = new Vector2(1.5f, -1.5f);
    }

    private static void InsetRect(RectTransform rt, float pixels)
    {
        rt.offsetMin += new Vector2(pixels, pixels);
        rt.offsetMax += new Vector2(-pixels, -pixels);
    }

    private void BuildDebugCanvasIfNeeded()
    {
        EnsureEventSystemExists();

        var canvasRoot = new GameObject("ExplorationLoadoutDebugCanvas");
        canvasRoot.transform.SetParent(transform, false);
        var canvas = canvasRoot.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvasRoot.AddComponent<CanvasScaler>().uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        canvasRoot.AddComponent<GraphicRaycaster>();

        var panel = CreateUiObject("Panel", canvasRoot.transform);
        panel.AddComponent<Image>().color = new Color(0f, 0f, 0f, 0.82f);
        AddPanelOutline(panel, new Color(0.75f, 0.75f, 0.85f, 0.5f));
        var panelRect = panel.GetComponent<RectTransform>();
        panelRect.anchorMin = new Vector2(0.05f, 0.08f);
        panelRect.anchorMax = new Vector2(0.95f, 0.92f);
        panelRect.offsetMin = new Vector2(10f, 10f);
        panelRect.offsetMax = new Vector2(-10f, -10f);

        _rootPanel = panel;
        _playerSlotsContainer = null;
        _bookSlotsContainer = null;

        _closeButton = CreateButton(panel.transform, "CloseButton", "Fechar", new Vector2(0.90f, 0.94f), new Vector2(0.985f, 0.985f));

        var detailsObj = CreateUiObject("Details", panel.transform);
        StretchRect(detailsObj.GetComponent<RectTransform>(), new Vector2(0.60f, 0.38f), new Vector2(0.97f, 0.94f));
        InsetRect(detailsObj.GetComponent<RectTransform>(), 6f);
        detailsObj.AddComponent<Image>().color = new Color(1f, 1f, 1f, 0.07f);
        AddPanelOutline(detailsObj, new Color(1f, 1f, 1f, 0.32f));
        CreateText(detailsObj.transform, "DetailsTitle", "Detalhes", new Vector2(0.04f, 0.88f), new Vector2(0.96f, 0.97f), 22f);
        BuildDetails(detailsObj.transform);

        var playerContainer = CreateUiObject("PlayerSlots", panel.transform);
        StretchRect(playerContainer.GetComponent<RectTransform>(), new Vector2(0.03f, 0.06f), new Vector2(0.49f, 0.35f));
        InsetRect(playerContainer.GetComponent<RectTransform>(), 6f);
        playerContainer.AddComponent<Image>().color = new Color(1f, 1f, 1f, 0.07f);
        AddPanelOutline(playerContainer, new Color(1f, 1f, 1f, 0.32f));
        CreateText(playerContainer.transform, "PlayerSlotsTitle", "Skills Player", new Vector2(0.03f, 0.80f), new Vector2(0.97f, 0.96f), 21f);
        _playerSlotsContainer = BuildLoadoutSlotContainer(playerContainer.transform, "PlayerSlotFrames");

        var bookContainer = CreateUiObject("BookSlots", panel.transform);
        StretchRect(bookContainer.GetComponent<RectTransform>(), new Vector2(0.51f, 0.06f), new Vector2(0.97f, 0.35f));
        InsetRect(bookContainer.GetComponent<RectTransform>(), 6f);
        bookContainer.AddComponent<Image>().color = new Color(1f, 1f, 1f, 0.07f);
        AddPanelOutline(bookContainer, new Color(1f, 1f, 1f, 0.32f));
        CreateText(bookContainer.transform, "BookSlotsTitle", "Skills Livro", new Vector2(0.03f, 0.80f), new Vector2(0.97f, 0.96f), 21f);
        _bookSlotsContainer = BuildLoadoutSlotContainer(bookContainer.transform, "BookSlotFrames");

        var catalogObj = CreateUiObject("Catalog", panel.transform);
        StretchRect(catalogObj.GetComponent<RectTransform>(), new Vector2(0.03f, 0.38f), new Vector2(0.58f, 0.94f));
        InsetRect(catalogObj.GetComponent<RectTransform>(), 6f);
        catalogObj.AddComponent<Image>().color = new Color(1f, 1f, 1f, 0.07f);
        AddPanelOutline(catalogObj, new Color(1f, 1f, 1f, 0.32f));
        CreateText(catalogObj.transform, "CatalogTitle", "Catalogo de Habilidades", new Vector2(0.04f, 0.88f), new Vector2(0.96f, 0.97f), 22f);

        var catalogGrid = CreateUiObject("CatalogContainer", catalogObj.transform);
        StretchRect(catalogGrid.GetComponent<RectTransform>(), new Vector2(0.04f, 0.04f), new Vector2(0.96f, 0.86f));
        var grid = catalogGrid.AddComponent<GridLayoutGroup>();
        grid.cellSize = new Vector2(120f, 120f);
        grid.spacing = new Vector2(8f, 8f);
        grid.constraint = GridLayoutGroup.Constraint.FixedColumnCount;
        grid.constraintCount = 5;
        _catalogContainer = catalogGrid.transform;
    }

    Transform BuildLoadoutSlotContainer(Transform parent, string name)
    {
        var slotsRow = CreateUiObject(name, parent);
        StretchRect(slotsRow.GetComponent<RectTransform>(), new Vector2(0.03f, 0.08f), new Vector2(0.97f, 0.76f));
        var layout = slotsRow.AddComponent<HorizontalLayoutGroup>();
        layout.spacing = 8f;
        layout.childAlignment = TextAnchor.MiddleCenter;
        layout.childControlWidth = false;
        layout.childControlHeight = false;
        layout.childForceExpandWidth = false;
        layout.childForceExpandHeight = false;
        return slotsRow.transform;
    }

    private void BuildDetails(Transform parent)
    {
        CreateText(parent, "NameLabel", "Nome", new Vector2(0.04f, 0.80f), new Vector2(0.96f, 0.87f), 13f);
        _detailNameText = CreateText(parent, "Name", "-", new Vector2(0.04f, 0.70f), new Vector2(0.96f, 0.79f), 22f, ellipsis: true);
        CreateText(parent, "DivinityLabel", "Divindade", new Vector2(0.04f, 0.62f), new Vector2(0.30f, 0.69f), 13f);
        _detailDivinityText = CreateText(parent, "Divinity", "-", new Vector2(0.32f, 0.62f), new Vector2(0.58f, 0.69f), 16f);
        CreateText(parent, "SkillTypeLabel", "Tipo", new Vector2(0.60f, 0.62f), new Vector2(0.78f, 0.69f), 13f);
        _detailSkillTypeText = CreateText(parent, "SkillType", "-", new Vector2(0.80f, 0.62f), new Vector2(0.96f, 0.69f), 16f);

        CreateText(parent, "DescriptionLabel", "Descricao", new Vector2(0.04f, 0.54f), new Vector2(0.96f, 0.61f), 13f);
        _detailDescriptionText = CreateText(parent, "Description", "", new Vector2(0.04f, 0.30f), new Vector2(0.96f, 0.53f), 16f);
        if (_detailDescriptionText != null)
        {
            _detailDescriptionText.enableWordWrapping = true;
            _detailDescriptionText.overflowMode = TextOverflowModes.Ellipsis;
        }

        CreateText(parent, "PowerLabel", "Poder", new Vector2(0.04f, 0.22f), new Vector2(0.30f, 0.28f), 13f);
        _detailPowerText = CreateText(parent, "Power", "-", new Vector2(0.04f, 0.15f), new Vector2(0.30f, 0.21f), 16f);

        CreateText(parent, "CostLabel", "Custo", new Vector2(0.32f, 0.22f), new Vector2(0.58f, 0.28f), 13f);
        _detailCostText = CreateText(parent, "Cost", "-", new Vector2(0.32f, 0.15f), new Vector2(0.58f, 0.21f), 16f);

        CreateText(parent, "RangeLabel", "Alcance", new Vector2(0.60f, 0.22f), new Vector2(0.86f, 0.28f), 13f);
        _detailRangeText = CreateText(parent, "Range", "-", new Vector2(0.60f, 0.15f), new Vector2(0.86f, 0.21f), 16f);

        var detailVisual = CreateUiObject("DetailVisual", parent);
        StretchRect(detailVisual.GetComponent<RectTransform>(), new Vector2(0.68f, 0.04f), new Vector2(0.96f, 0.28f));
        var detailBgObj = CreateUiObject("BackgroundPaint", detailVisual.transform);
        _detailBackgroundImage = detailBgObj.AddComponent<Image>();
        StretchRect(detailBgObj.GetComponent<RectTransform>(), Vector2.zero, Vector2.one);
        _detailBackgroundImage.enabled = false;
        var detailFrameObj = CreateUiObject("Frame", detailVisual.transform);
        _detailFrameImage = detailFrameObj.AddComponent<Image>();
        StretchRect(detailFrameObj.GetComponent<RectTransform>(), Vector2.zero, Vector2.one);
        _detailFrameImage.enabled = false;
        var detailIconObj = CreateUiObject("Icon", detailVisual.transform);
        _detailIconImage = detailIconObj.AddComponent<Image>();
        StretchRect(detailIconObj.GetComponent<RectTransform>(), new Vector2(0.12f, 0.12f), new Vector2(0.88f, 0.88f));
        _detailIconImage.enabled = false;
    }

    private static GameObject CreateUiObject(string name, Transform parent)
    {
        var go = new GameObject(name, typeof(RectTransform));
        go.transform.SetParent(parent, false);
        return go;
    }

    private static void StretchRect(RectTransform rect, Vector2 min, Vector2 max)
    {
        rect.anchorMin = min;
        rect.anchorMax = max;
        rect.offsetMin = Vector2.zero;
        rect.offsetMax = Vector2.zero;
    }

    private static TMP_Text CreateText(Transform parent, string name, string text, Vector2 min, Vector2 max, float size, bool ellipsis = false)
    {
        var go = CreateUiObject(name, parent);
        var txt = go.AddComponent<TextMeshProUGUI>();
        txt.text = text;
        txt.fontSize = size;
        txt.color = Color.white;
        txt.alignment = TextAlignmentOptions.Left;
        if (ellipsis)
        {
            txt.enableWordWrapping = false;
            txt.overflowMode = TextOverflowModes.Ellipsis;
        }
        StretchRect(go.GetComponent<RectTransform>(), min, max);
        return txt;
    }

    private static Button CreateButton(Transform parent, string name, string text, Vector2 min, Vector2 max)
    {
        var go = CreateUiObject(name, parent);
        var image = go.AddComponent<Image>();
        image.color = new Color(1f, 1f, 1f, 0.16f);
        var button = go.AddComponent<Button>();
        var txt = CreateText(go.transform, "Text", text, Vector2.zero, Vector2.one, 20f);
        txt.alignment = TextAlignmentOptions.Center;
        StretchRect(go.GetComponent<RectTransform>(), min, max);
        return button;
    }

    private static void EnsureEventSystemExists()
    {
        if (FindObjectOfType<EventSystem>() != null) return;
        var eventSystem = new GameObject("EventSystem", typeof(EventSystem), typeof(StandaloneInputModule));
        DontDestroyOnLoad(eventSystem);
    }
}
