using System;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using Logic.Scripts.GameDomain.Services.Skills;
using UnityEngine.EventSystems;

public class ExplorationLoadoutUIView : MonoBehaviour
{
    [Serializable]
    public class SkillSlotUiRef
    {
        public Button Button;
        public TMP_Text NameText;
        public TMP_Text CostText;
        public Image IconImage;
        public Image SelectionOutline;
    }

    [Header("Root")]
    [SerializeField] private GameObject _rootPanel;
    [SerializeField] private Button _closeButton;
    [SerializeField] private bool _autoGenerateDebugCanvas;

    [Header("Loadout Slots")]
    [SerializeField] private List<SkillSlotUiRef> _playerSlots = new List<SkillSlotUiRef>(4);
    [SerializeField] private List<SkillSlotUiRef> _bookSlots = new List<SkillSlotUiRef>(4);

    [Header("Catalog")]
    [SerializeField] private Transform _catalogContainer;
    [SerializeField] private ExplorationSkillCatalogItemView _catalogItemPrefab;

    [Header("Details")]
    [SerializeField] private TMP_Text _detailNameText;
    [SerializeField] private TMP_Text _detailDescriptionText;
    [SerializeField] private TMP_Text _detailPowerText;
    [SerializeField] private TMP_Text _detailCostText;
    [SerializeField] private TMP_Text _detailRangeText;
    [SerializeField] private TMP_Text _detailCooldownText;
    [SerializeField] private Image _detailIconImage;

    private void Awake()
    {
        if (_autoGenerateDebugCanvas)
            BuildDebugCanvasIfNeeded();
    }

    public bool IsVisible => _rootPanel != null && _rootPanel.activeSelf;

    public void Init()
    {
        SetVisible(false);
    }

    public void RegisterCallbacks(Action onClose, Action<int> onPlayerSlotClicked, Action<int> onBookSlotClicked)
    {
        if (_closeButton != null)
        {
            _closeButton.onClick.RemoveAllListeners();
            _closeButton.onClick.AddListener(() => onClose?.Invoke());
        }

        RegisterSlotCallbacks(_playerSlots, onPlayerSlotClicked);
        RegisterSlotCallbacks(_bookSlots, onBookSlotClicked);
    }

    public void SetVisible(bool visible)
    {
        if (_rootPanel != null) _rootPanel.SetActive(visible);
    }

    public void SetSlotData(SkillLoadoutUnitType unitType, int slotIndex, SkillDataSO skill)
    {
        SkillSlotUiRef slot = GetSlot(unitType, slotIndex);
        if (slot == null) return;

        if (slot.NameText != null) slot.NameText.SetText(skill != null ? skill.SkillName : "-");
        if (slot.CostText != null) slot.CostText.SetText(skill != null ? skill.Cost.ToString() : "0");
        if (slot.IconImage != null)
        {
            slot.IconImage.sprite = skill != null ? skill.Icon : null;
            slot.IconImage.enabled = slot.IconImage.sprite != null;
        }
    }

    public void SetSelectedSlot(SkillLoadoutUnitType unitType, int slotIndex)
    {
        SetSelectionState(_playerSlots, false);
        SetSelectionState(_bookSlots, false);

        SkillSlotUiRef selected = GetSlot(unitType, slotIndex);
        if (selected?.SelectionOutline != null) selected.SelectionOutline.enabled = true;
    }

    public void ClearCatalog()
    {
        if (_catalogContainer == null) return;
        for (int i = _catalogContainer.childCount - 1; i >= 0; i--)
            Destroy(_catalogContainer.GetChild(i).gameObject);
    }

    public ExplorationSkillCatalogItemView CreateCatalogItem()
    {
        if (_catalogContainer == null) return null;
        if (_catalogItemPrefab == null)
            return CreateRuntimeCatalogItem(_catalogContainer);
        return Instantiate(_catalogItemPrefab, _catalogContainer);
    }

    public void ShowSkillDetails(SkillDataSO skill)
    {
        if (_detailNameText != null) _detailNameText.SetText(skill != null ? skill.SkillName : "-");
        if (_detailDescriptionText != null) _detailDescriptionText.SetText(skill != null ? skill.Description : string.Empty);
        if (_detailPowerText != null) _detailPowerText.SetText(skill != null ? skill.Power.ToString() : "-");
        if (_detailCostText != null) _detailCostText.SetText(skill != null ? skill.Cost.ToString() : "-");
        if (_detailRangeText != null) _detailRangeText.SetText(skill != null ? skill.Range.ToString("0.##") : "-");
        if (_detailCooldownText != null) _detailCooldownText.SetText(skill != null ? skill.CoolDown.ToString("0.##") : "-");
        if (_detailIconImage != null)
        {
            _detailIconImage.sprite = skill != null ? skill.Icon : null;
            _detailIconImage.enabled = _detailIconImage.sprite != null;
        }
    }

    private static void RegisterSlotCallbacks(List<SkillSlotUiRef> slots, Action<int> onClicked)
    {
        if (slots == null) return;
        for (int i = 0; i < slots.Count; i++)
        {
            int index = i;
            var slot = slots[i];
            if (slot?.Button == null) continue;
            slot.Button.onClick.RemoveAllListeners();
            slot.Button.onClick.AddListener(() => onClicked?.Invoke(index));
        }
    }

    private static void SetSelectionState(List<SkillSlotUiRef> slots, bool selected)
    {
        if (slots == null) return;
        for (int i = 0; i < slots.Count; i++)
        {
            var slot = slots[i];
            if (slot?.SelectionOutline != null) slot.SelectionOutline.enabled = selected;
        }
    }

    private SkillSlotUiRef GetSlot(SkillLoadoutUnitType unitType, int slotIndex)
    {
        List<SkillSlotUiRef> slots = unitType == SkillLoadoutUnitType.Book ? _bookSlots : _playerSlots;
        if (slots == null || slotIndex < 0 || slotIndex >= slots.Count) return null;
        return slots[slotIndex];
    }

    private void BuildDebugCanvasIfNeeded()
    {
        EnsureEventSystemExists();

        var canvasRoot = new GameObject("ExplorationLoadoutDebugCanvas");
        canvasRoot.transform.SetParent(transform, false);
        var canvas = canvasRoot.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvasRoot.AddComponent<CanvasScaler>().uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        canvasRoot.AddComponent<GraphicRaycaster>();

        var panel = CreateUiObject("Panel", canvasRoot.transform);
        var panelImage = panel.AddComponent<Image>();
        panelImage.color = new Color(0f, 0f, 0f, 0.8f);
        var panelRect = panel.GetComponent<RectTransform>();
        panelRect.anchorMin = new Vector2(0.05f, 0.08f);
        panelRect.anchorMax = new Vector2(0.95f, 0.92f);
        panelRect.offsetMin = Vector2.zero;
        panelRect.offsetMax = Vector2.zero;

        _rootPanel = panel;
        _playerSlots.Clear();
        _bookSlots.Clear();

        _closeButton = CreateButton(panel.transform, "CloseButton", "Fechar", new Vector2(0.92f, 0.95f), new Vector2(0.99f, 0.99f));

        var catalogObj = CreateUiObject("Catalog", panel.transform);
        StretchRect(catalogObj.GetComponent<RectTransform>(), new Vector2(0.03f, 0.52f), new Vector2(0.58f, 0.94f));
        var catalogImage = catalogObj.AddComponent<Image>();
        catalogImage.color = new Color(1f, 1f, 1f, 0.08f);
        CreateText(catalogObj.transform, "CatalogTitle", "Catalogo de Habilidades", new Vector2(0.02f, 0.86f), new Vector2(0.98f, 0.98f), 24f);
        _catalogContainer = BuildCatalogScrollArea(catalogObj.transform);

        var detailsObj = CreateUiObject("Details", panel.transform);
        StretchRect(detailsObj.GetComponent<RectTransform>(), new Vector2(0.60f, 0.52f), new Vector2(0.97f, 0.94f));
        var detailsImage = detailsObj.AddComponent<Image>();
        detailsImage.color = new Color(1f, 1f, 1f, 0.08f);
        CreateText(detailsObj.transform, "DetailsTitle", "Detalhes", new Vector2(0.03f, 0.86f), new Vector2(0.97f, 0.98f), 24f);
        BuildDetails(detailsObj.transform);

        var playerContainer = CreateUiObject("PlayerSlots", panel.transform);
        StretchRect(playerContainer.GetComponent<RectTransform>(), new Vector2(0.03f, 0.06f), new Vector2(0.49f, 0.46f));
        var playerBg = playerContainer.AddComponent<Image>();
        playerBg.color = new Color(1f, 1f, 1f, 0.08f);
        BuildSlotRow(playerContainer.transform, _playerSlots, "Skills Player", "P");

        var bookContainer = CreateUiObject("BookSlots", panel.transform);
        StretchRect(bookContainer.GetComponent<RectTransform>(), new Vector2(0.51f, 0.06f), new Vector2(0.97f, 0.46f));
        var bookBg = bookContainer.AddComponent<Image>();
        bookBg.color = new Color(1f, 1f, 1f, 0.08f);
        BuildSlotRow(bookContainer.transform, _bookSlots, "Skills Livro", "L");
    }

    private void BuildSlotRow(Transform parent, List<SkillSlotUiRef> targetSlots, string title, string prefix)
    {
        CreateText(parent, $"{title}Title", title, new Vector2(0.02f, 0.83f), new Vector2(0.98f, 0.98f), 24f);
        for (int i = 0; i < 4; i++)
        {
            float minX = 0.01f + i * 0.245f;
            float maxX = minX + 0.235f;
            var slotObj = CreateUiObject($"{prefix}Slot{i}", parent);
            StretchRect(slotObj.GetComponent<RectTransform>(), new Vector2(minX, 0.10f), new Vector2(maxX, 0.80f));

            var button = slotObj.AddComponent<Button>();
            var image = slotObj.AddComponent<Image>();
            image.color = new Color(1f, 1f, 1f, 0.14f);
            var outlineObj = CreateUiObject("Selected", slotObj.transform);
            var outline = outlineObj.AddComponent<Image>();
            outline.color = new Color(1f, 0.85f, 0.2f, 0.45f);
            StretchRect(outlineObj.GetComponent<RectTransform>(), Vector2.zero, Vector2.one);
            outline.enabled = false;

            var name = CreateText(slotObj.transform, "Name", "-", new Vector2(0.04f, 0.58f), new Vector2(0.96f, 0.95f), 17f);
            var cost = CreateText(slotObj.transform, "Cost", "0", new Vector2(0.04f, 0.1f), new Vector2(0.45f, 0.5f), 18f);
            var iconObj = CreateUiObject("Icon", slotObj.transform);
            var icon = iconObj.AddComponent<Image>();
            StretchRect(iconObj.GetComponent<RectTransform>(), new Vector2(0.52f, 0.12f), new Vector2(0.92f, 0.52f));
            icon.enabled = false;

            targetSlots.Add(new SkillSlotUiRef
            {
                Button = button,
                NameText = name,
                CostText = cost,
                IconImage = icon,
                SelectionOutline = outline
            });
        }
    }

    private void BuildDetails(Transform parent)
    {
        CreateText(parent, "NameLabel", "Nome", new Vector2(0.03f, 0.78f), new Vector2(0.97f, 0.86f), 14f);
        _detailNameText = CreateText(parent, "Name", "-", new Vector2(0.03f, 0.66f), new Vector2(0.97f, 0.78f), 24f);

        CreateText(parent, "DescriptionLabel", "Descricao", new Vector2(0.03f, 0.58f), new Vector2(0.97f, 0.66f), 14f);
        _detailDescriptionText = CreateText(parent, "Description", "", new Vector2(0.03f, 0.42f), new Vector2(0.97f, 0.58f), 18f);

        CreateText(parent, "PowerLabel", "Poder", new Vector2(0.03f, 0.33f), new Vector2(0.28f, 0.40f), 14f);
        _detailPowerText = CreateText(parent, "Power", "-", new Vector2(0.03f, 0.25f), new Vector2(0.28f, 0.33f), 18f);

        CreateText(parent, "CostLabel", "Custo", new Vector2(0.30f, 0.33f), new Vector2(0.55f, 0.40f), 14f);
        _detailCostText = CreateText(parent, "Cost", "-", new Vector2(0.30f, 0.25f), new Vector2(0.55f, 0.33f), 18f);

        CreateText(parent, "RangeLabel", "Alcance", new Vector2(0.57f, 0.33f), new Vector2(0.82f, 0.40f), 14f);
        _detailRangeText = CreateText(parent, "Range", "-", new Vector2(0.57f, 0.25f), new Vector2(0.82f, 0.33f), 18f);

        CreateText(parent, "CooldownLabel", "Cooldown", new Vector2(0.03f, 0.16f), new Vector2(0.55f, 0.23f), 14f);
        _detailCooldownText = CreateText(parent, "Cooldown", "-", new Vector2(0.03f, 0.08f), new Vector2(0.55f, 0.16f), 18f);

        var iconObj = CreateUiObject("Icon", parent);
        _detailIconImage = iconObj.AddComponent<Image>();
        StretchRect(iconObj.GetComponent<RectTransform>(), new Vector2(0.75f, 0.05f), new Vector2(0.95f, 0.23f));
        _detailIconImage.enabled = false;
    }

    private Transform BuildCatalogScrollArea(Transform parent)
    {
        var viewport = CreateUiObject("Viewport", parent);
        StretchRect(viewport.GetComponent<RectTransform>(), new Vector2(0.02f, 0.04f), new Vector2(0.98f, 0.84f));
        var viewportImage = viewport.AddComponent<Image>();
        viewportImage.color = new Color(0f, 0f, 0f, 0.15f);
        viewport.AddComponent<Mask>().showMaskGraphic = false;

        var content = CreateUiObject("Content", viewport.transform);
        var contentRect = content.GetComponent<RectTransform>();
        contentRect.anchorMin = new Vector2(0f, 1f);
        contentRect.anchorMax = new Vector2(1f, 1f);
        contentRect.pivot = new Vector2(0.5f, 1f);
        contentRect.anchoredPosition = Vector2.zero;
        contentRect.sizeDelta = new Vector2(0f, 0f);

        var scrollRect = parent.gameObject.AddComponent<ScrollRect>();
        scrollRect.viewport = viewport.GetComponent<RectTransform>();
        scrollRect.content = contentRect;
        scrollRect.horizontal = false;
        scrollRect.vertical = true;
        scrollRect.movementType = ScrollRect.MovementType.Clamped;
        scrollRect.scrollSensitivity = 30f;

        return content.transform;
    }

    private ExplorationSkillCatalogItemView CreateRuntimeCatalogItem(Transform parent)
    {
        var row = CreateUiObject("CatalogItem", parent);
        var rowRect = row.GetComponent<RectTransform>();
        rowRect.anchorMin = new Vector2(0f, 1f);
        rowRect.anchorMax = new Vector2(1f, 1f);
        rowRect.pivot = new Vector2(0.5f, 1f);
        rowRect.sizeDelta = new Vector2(0f, 64f);
        rowRect.anchoredPosition = new Vector2(0f, -68f * (parent.childCount - 1));
        float contentHeight = 68f * (parent.childCount + 1);
        if (parent is RectTransform parentRect)
            parentRect.sizeDelta = new Vector2(parentRect.sizeDelta.x, contentHeight);

        var button = row.AddComponent<Button>();
        var image = row.AddComponent<Image>();
        image.color = new Color(1f, 1f, 1f, 0.12f);

        var name = CreateText(row.transform, "Name", "-", new Vector2(0.08f, 0.15f), new Vector2(0.96f, 0.85f), 20f);
        var iconObj = CreateUiObject("Icon", row.transform);
        var icon = iconObj.AddComponent<Image>();
        StretchRect(iconObj.GetComponent<RectTransform>(), new Vector2(0.01f, 0.15f), new Vector2(0.07f, 0.85f));
        icon.enabled = false;

        var view = row.AddComponent<ExplorationSkillCatalogItemView>();
        view.ConfigureRuntimeReferences(button, name, icon);
        return view;
    }

    private static GameObject CreateUiObject(string name, Transform parent)
    {
        var go = new GameObject(name, typeof(RectTransform));
        go.transform.SetParent(parent, false);
        return go;
    }

    private static void StretchRect(RectTransform rect, Vector2 min, Vector2 max)
    {
        rect.anchorMin = min;
        rect.anchorMax = max;
        rect.offsetMin = Vector2.zero;
        rect.offsetMax = Vector2.zero;
    }

    private static TMP_Text CreateText(Transform parent, string name, string text, Vector2 min, Vector2 max, float size)
    {
        var go = CreateUiObject(name, parent);
        var txt = go.AddComponent<TextMeshProUGUI>();
        txt.text = text;
        txt.fontSize = size;
        txt.color = Color.white;
        txt.alignment = TextAlignmentOptions.Left;
        StretchRect(go.GetComponent<RectTransform>(), min, max);
        return txt;
    }

    private static Button CreateButton(Transform parent, string name, string text, Vector2 min, Vector2 max)
    {
        var go = CreateUiObject(name, parent);
        var image = go.AddComponent<Image>();
        image.color = new Color(1f, 1f, 1f, 0.16f);
        var button = go.AddComponent<Button>();
        var txt = CreateText(go.transform, "Text", text, Vector2.zero, Vector2.one, 20f);
        txt.alignment = TextAlignmentOptions.Center;
        StretchRect(go.GetComponent<RectTransform>(), min, max);
        return button;
    }

    private static void EnsureEventSystemExists()
    {
        if (FindObjectOfType<EventSystem>() != null) return;
        var eventSystem = new GameObject("EventSystem", typeof(EventSystem), typeof(StandaloneInputModule));
        DontDestroyOnLoad(eventSystem);
    }
}
