using System;
using System.Collections.Generic;
using DG.Tweening;
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using Logic.Scripts.GameDomain.Services.Skills;
using Logic.Scripts.GameDomain.MVC.ExplorationLoadout;
using UnityEngine.EventSystems;

public class ExplorationLoadoutUIView : MonoBehaviour, IExplorationLoadoutView
{
    [Serializable]
    public class SkillSlotUiRef
    {
        public Button Button;
        public Image BackgroundImage;
        public Image FrameImage;
        public Image IconImage;
        public TMP_Text NameText;
        public TMP_Text CostText;
        public Image SelectionOutline;
    }

    [Header("Root")]
    [SerializeField] private GameObject _rootPanel;
    [SerializeField] private Button _closeButton;
    [SerializeField] private bool _autoGenerateDebugCanvas;

    [Header("Loadout Slots")]
    [SerializeField] private List<SkillSlotUiRef> _playerSlots = new List<SkillSlotUiRef>(4);
    [SerializeField] private List<SkillSlotUiRef> _bookSlots = new List<SkillSlotUiRef>(4);

    [Header("Catalog")]
    [Tooltip("Parent transform where skill frames are spawned (Grid/Layout group in your scene).")]
    [SerializeField] private Transform _catalogContainer;
    [Tooltip("SkillFrame.prefab — must include LoadoutSkillFrameView.")]
    [SerializeField] private LoadoutSkillFrameView _skillFramePrefab;
    [Tooltip("Opcional. Dropdown TMP no prefab da cena (mesma ordem que ExplorationLoadoutSkillFilter).")]
    [SerializeField] private TMP_Dropdown _skillCategoryDropdown;
    [Tooltip("Opcional. Dropdown TMP para filtrar por divindade.")]
    [SerializeField] private TMP_Dropdown _divinityCategoryDropdown;

    [Header("Details")]
    [SerializeField] private TMP_Text _detailNameText;
    [SerializeField] private TMP_Text _detailDivinityText;
    [SerializeField] private TMP_Text _detailDescriptionText;
    [SerializeField] private TMP_Text _detailPowerText;
    [SerializeField] private TMP_Text _detailCostText;
    [SerializeField] private TMP_Text _detailRangeText;
    [SerializeField] private Image _detailBackgroundImage;
    [SerializeField] private Image _detailFrameImage;
    [SerializeField] private Image _detailIconImage;

    private ISkillVisualCatalog _visualCatalog;
    private Action<ExplorationLoadoutSkillFilter> _onCatalogFilterChanged;
    private Action<ExplorationLoadoutDivinityFilter> _onDivinityFilterChanged;
    private readonly List<LoadoutSkillFrameView> _catalogItems = new List<LoadoutSkillFrameView>(16);

    private void Awake()
    {
        if (_autoGenerateDebugCanvas)
            BuildDebugCanvasIfNeeded();
        EnsureHiddenOnSceneLoad();
    }

    private void EnsureHiddenOnSceneLoad()
    {
        SetVisible(false);
    }

    public bool IsVisible => _rootPanel != null && _rootPanel.activeSelf;

    public void Init(ISkillVisualCatalog visualCatalog = null)
    {
        _visualCatalog = visualCatalog;
        SetVisible(false);
    }

    public void RegisterCallbacks(Action onClose, Action<int> onPlayerSlotClicked, Action<int> onBookSlotClicked,
        Action<ExplorationLoadoutSkillFilter> onCatalogFilterChanged = null,
        Action<ExplorationLoadoutDivinityFilter> onDivinityFilterChanged = null)
    {
        if (_closeButton != null)
        {
            _closeButton.onClick.RemoveAllListeners();
            _closeButton.onClick.AddListener(() => onClose?.Invoke());
        }

        RegisterSlotCallbacks(_playerSlots, onPlayerSlotClicked);
        RegisterSlotCallbacks(_bookSlots, onBookSlotClicked);

        _onCatalogFilterChanged = onCatalogFilterChanged;
        _onDivinityFilterChanged = onDivinityFilterChanged;
        WireSkillCategoryDropdown();
        WireDivinityCategoryDropdown();
    }

    private void WireSkillCategoryDropdown()
    {
        if (_skillCategoryDropdown == null) return;
        _skillCategoryDropdown.onValueChanged.RemoveListener(OnSkillCategoryDropdownValueChanged);
        _skillCategoryDropdown.ClearOptions();
        var opts = new List<string>(5);
        for (int i = 0; i <= (int)ExplorationLoadoutSkillFilter.Buff; i++)
            opts.Add(ExplorationLoadoutSkillFilterUtil.DisplayLabel((ExplorationLoadoutSkillFilter)i));
        _skillCategoryDropdown.AddOptions(opts);
        _skillCategoryDropdown.SetValueWithoutNotify(0);
        _skillCategoryDropdown.onValueChanged.AddListener(OnSkillCategoryDropdownValueChanged);
    }

    private void OnSkillCategoryDropdownValueChanged(int index)
    {
        if (index < 0 || index > (int)ExplorationLoadoutSkillFilter.Buff) return;
        _onCatalogFilterChanged?.Invoke((ExplorationLoadoutSkillFilter)index);
    }

    private void WireDivinityCategoryDropdown()
    {
        if (_divinityCategoryDropdown == null) return;
        _divinityCategoryDropdown.onValueChanged.RemoveListener(OnDivinityCategoryDropdownValueChanged);
        _divinityCategoryDropdown.ClearOptions();
        var opts = new List<string>(6);
        for (int i = 0; i <= (int)ExplorationLoadoutDivinityFilter.Iara; i++)
            opts.Add(ExplorationLoadoutDivinityFilterUtil.DisplayLabel((ExplorationLoadoutDivinityFilter)i));
        _divinityCategoryDropdown.AddOptions(opts);
        _divinityCategoryDropdown.SetValueWithoutNotify(0);
        _divinityCategoryDropdown.onValueChanged.AddListener(OnDivinityCategoryDropdownValueChanged);
    }

    private void OnDivinityCategoryDropdownValueChanged(int index)
    {
        if (index < 0 || index > (int)ExplorationLoadoutDivinityFilter.Iara) return;
        _onDivinityFilterChanged?.Invoke((ExplorationLoadoutDivinityFilter)index);
    }

    public void SetVisible(bool visible)
    {
        if (_rootPanel != null) _rootPanel.SetActive(visible);
    }

    public void SetSlotData(SkillLoadoutUnitType unitType, int slotIndex, SkillDataSO skill)
    {
        SkillSlotUiRef slot = GetSlot(unitType, slotIndex);
        if (slot == null) return;

        if (slot.NameText != null) slot.NameText.SetText(skill != null ? skill.SkillName : "-");
        if (slot.CostText != null)
        {
            if (skill == null) slot.CostText.SetText("0");
            else if (skill.SkillType == SkillType.Passive) slot.CostText.SetText("-");
            else slot.CostText.SetText(skill.Cost.ToString());
        }
        ApplySlotVisualLayers(slot, skill);
    }

    private void ApplySlotVisualLayers(SkillSlotUiRef slot, SkillDataSO skill)
    {
        if (slot == null) return;

        if (skill == null) {
            ClearSlotVisualLayers(slot);
            return;
        }

        if (_visualCatalog != null && _visualCatalog.TryGetLayerSprites(skill.Divinity, skill.SkillType,
                out var bg, out var frame)) {
            if (slot.BackgroundImage != null) {
                slot.BackgroundImage.sprite = bg;
                slot.BackgroundImage.enabled = bg != null;
                if (bg != null) slot.BackgroundImage.color = Color.white;
            }
            if (slot.FrameImage != null) {
                slot.FrameImage.sprite = frame;
                slot.FrameImage.enabled = frame != null;
                if (frame != null) slot.FrameImage.color = Color.white;
            }
        } else {
            if (slot.BackgroundImage != null) {
                slot.BackgroundImage.sprite = null;
                slot.BackgroundImage.enabled = false;
            }
            if (slot.FrameImage != null) {
                slot.FrameImage.sprite = null;
                slot.FrameImage.enabled = false;
            }
        }

        if (slot.IconImage != null) {
            slot.IconImage.sprite = skill.Icon;
            slot.IconImage.enabled = skill.Icon != null;
            if (skill.Icon != null) slot.IconImage.color = Color.white;
        }
    }

    private static void ClearSlotVisualLayers(SkillSlotUiRef slot)
    {
        if (slot.BackgroundImage != null) {
            slot.BackgroundImage.sprite = null;
            slot.BackgroundImage.enabled = false;
        }
        if (slot.FrameImage != null) {
            slot.FrameImage.sprite = null;
            slot.FrameImage.enabled = false;
        }
        if (slot.IconImage != null) {
            slot.IconImage.sprite = null;
            slot.IconImage.enabled = false;
        }
    }

    public void SetSelectedSlot(SkillLoadoutUnitType unitType, int slotIndex)
    {
        SetSelectionState(_playerSlots, false);
        SetSelectionState(_bookSlots, false);

        SkillSlotUiRef selected = GetSlot(unitType, slotIndex);
        if (selected?.SelectionOutline != null) selected.SelectionOutline.enabled = true;
    }

    public void ClearSlotSelection()
    {
        SetSelectionState(_playerSlots, false);
        SetSelectionState(_bookSlots, false);
    }

    public void PlayInvalidAssignFeedback()
    {
        if (_rootPanel == null) return;
        var rect = _rootPanel.GetComponent<RectTransform>();
        if (rect == null) return;
        DOTween.Kill(rect, true);
        rect.DOShakeAnchorPos(0.35f, strength: 14f, vibrato: 14, randomness: 50f, fadeOut: true);
    }

    public void ClearCatalog()
    {
        _catalogItems.Clear();
        if (_catalogContainer == null) return;
        for (int i = _catalogContainer.childCount - 1; i >= 0; i--)
            Destroy(_catalogContainer.GetChild(i).gameObject);
    }

    public LoadoutSkillFrameView CreateCatalogItem()
    {
        if (_catalogContainer == null || _skillFramePrefab == null) return null;
        LoadoutSkillFrameView frame = Instantiate(_skillFramePrefab, _catalogContainer);
        _catalogItems.Add(frame);
        return frame;
    }

    public void SetSelectedCatalogSkill(SkillDataSO skill)
    {
        for (int i = 0; i < _catalogItems.Count; i++)
        {
            LoadoutSkillFrameView frame = _catalogItems[i];
            if (frame == null) continue;
            frame.SetCatalogSelected(frame.BoundSkill == skill);
        }
    }

    public void FinalizeCatalogScroll()
    {
        if (_catalogContainer is not RectTransform rt) return;
        LayoutRebuilder.ForceRebuildLayoutImmediate(rt);
        Canvas.ForceUpdateCanvases();
    }

    public void ShowSkillDetails(SkillDataSO skill)
    {
        if (_detailNameText != null) _detailNameText.SetText(skill != null ? skill.SkillName : "-");
        if (_detailDivinityText != null)
            _detailDivinityText.SetText(skill != null ? SkillDivinityUtil.DisplayLabel(skill.Divinity) : "-");
        if (_detailDescriptionText != null) _detailDescriptionText.SetText(skill != null ? skill.Description : string.Empty);
        if (_detailPowerText != null) _detailPowerText.SetText(skill != null ? skill.Power.ToString() : "-");
        if (_detailCostText != null)
        {
            if (skill == null) _detailCostText.SetText("-");
            else if (skill.SkillType == SkillType.Passive) _detailCostText.SetText("-");
            else _detailCostText.SetText(skill.Cost.ToString());
        }
        if (_detailRangeText != null) _detailRangeText.SetText(skill != null ? skill.Range.ToString("0.##") : "-");
        ApplyDetailVisualLayers(skill);
    }

    private void ApplyDetailVisualLayers(SkillDataSO skill)
    {
        if (skill == null) {
            if (_detailBackgroundImage != null) {
                _detailBackgroundImage.sprite = null;
                _detailBackgroundImage.enabled = false;
            }
            if (_detailFrameImage != null) {
                _detailFrameImage.sprite = null;
                _detailFrameImage.enabled = false;
            }
            if (_detailIconImage != null) {
                _detailIconImage.sprite = null;
                _detailIconImage.enabled = false;
            }
            return;
        }

        if (_visualCatalog != null && _visualCatalog.TryGetLayerSprites(skill.Divinity, skill.SkillType,
                out var bg, out var frame)) {
            if (_detailBackgroundImage != null) {
                _detailBackgroundImage.sprite = bg;
                _detailBackgroundImage.enabled = bg != null;
                if (bg != null) _detailBackgroundImage.color = Color.white;
            }
            if (_detailFrameImage != null) {
                _detailFrameImage.sprite = frame;
                _detailFrameImage.enabled = frame != null;
                if (frame != null) _detailFrameImage.color = Color.white;
            }
        } else {
            if (_detailBackgroundImage != null) {
                _detailBackgroundImage.sprite = null;
                _detailBackgroundImage.enabled = false;
            }
            if (_detailFrameImage != null) {
                _detailFrameImage.sprite = null;
                _detailFrameImage.enabled = false;
            }
        }

        if (_detailIconImage != null) {
            _detailIconImage.sprite = skill.Icon;
            _detailIconImage.enabled = skill.Icon != null;
            if (skill.Icon != null) _detailIconImage.color = Color.white;
        }
    }

    private static void RegisterSlotCallbacks(List<SkillSlotUiRef> slots, Action<int> onClicked)
    {
        if (slots == null) return;
        for (int i = 0; i < slots.Count; i++)
        {
            int index = i;
            var slot = slots[i];
            if (slot?.Button == null) continue;
            slot.Button.onClick.RemoveAllListeners();
            slot.Button.onClick.AddListener(() => onClicked?.Invoke(index));
        }
    }

    private static void SetSelectionState(List<SkillSlotUiRef> slots, bool selected)
    {
        if (slots == null) return;
        for (int i = 0; i < slots.Count; i++)
        {
            var slot = slots[i];
            if (slot?.SelectionOutline != null) slot.SelectionOutline.enabled = selected;
        }
    }

    private SkillSlotUiRef GetSlot(SkillLoadoutUnitType unitType, int slotIndex)
    {
        List<SkillSlotUiRef> slots = unitType == SkillLoadoutUnitType.Book ? _bookSlots : _playerSlots;
        if (slots == null || slotIndex < 0 || slotIndex >= slots.Count) return null;
        return slots[slotIndex];
    }

    private static void AddPanelOutline(GameObject go, Color outlineColor)
    {
        var o = go.AddComponent<Outline>();
        o.effectColor = outlineColor;
        o.effectDistance = new Vector2(1.5f, -1.5f);
    }

    private static void InsetRect(RectTransform rt, float pixels)
    {
        rt.offsetMin += new Vector2(pixels, pixels);
        rt.offsetMax += new Vector2(-pixels, -pixels);
    }

    private void BuildDebugCanvasIfNeeded()
    {
        EnsureEventSystemExists();

        var canvasRoot = new GameObject("ExplorationLoadoutDebugCanvas");
        canvasRoot.transform.SetParent(transform, false);
        var canvas = canvasRoot.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvasRoot.AddComponent<CanvasScaler>().uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        canvasRoot.AddComponent<GraphicRaycaster>();

        var panel = CreateUiObject("Panel", canvasRoot.transform);
        panel.AddComponent<Image>().color = new Color(0f, 0f, 0f, 0.82f);
        AddPanelOutline(panel, new Color(0.75f, 0.75f, 0.85f, 0.5f));
        var panelRect = panel.GetComponent<RectTransform>();
        panelRect.anchorMin = new Vector2(0.05f, 0.08f);
        panelRect.anchorMax = new Vector2(0.95f, 0.92f);
        panelRect.offsetMin = new Vector2(10f, 10f);
        panelRect.offsetMax = new Vector2(-10f, -10f);

        _rootPanel = panel;
        _playerSlots.Clear();
        _bookSlots.Clear();

        _closeButton = CreateButton(panel.transform, "CloseButton", "Fechar", new Vector2(0.90f, 0.94f), new Vector2(0.985f, 0.985f));

        var detailsObj = CreateUiObject("Details", panel.transform);
        StretchRect(detailsObj.GetComponent<RectTransform>(), new Vector2(0.60f, 0.38f), new Vector2(0.97f, 0.94f));
        InsetRect(detailsObj.GetComponent<RectTransform>(), 6f);
        detailsObj.AddComponent<Image>().color = new Color(1f, 1f, 1f, 0.07f);
        AddPanelOutline(detailsObj, new Color(1f, 1f, 1f, 0.32f));
        CreateText(detailsObj.transform, "DetailsTitle", "Detalhes", new Vector2(0.04f, 0.88f), new Vector2(0.96f, 0.97f), 22f);
        BuildDetails(detailsObj.transform);

        var playerContainer = CreateUiObject("PlayerSlots", panel.transform);
        StretchRect(playerContainer.GetComponent<RectTransform>(), new Vector2(0.03f, 0.06f), new Vector2(0.49f, 0.35f));
        InsetRect(playerContainer.GetComponent<RectTransform>(), 6f);
        playerContainer.AddComponent<Image>().color = new Color(1f, 1f, 1f, 0.07f);
        AddPanelOutline(playerContainer, new Color(1f, 1f, 1f, 0.32f));
        BuildSlotRow(playerContainer.transform, _playerSlots, "Skills Player", "P");

        var bookContainer = CreateUiObject("BookSlots", panel.transform);
        StretchRect(bookContainer.GetComponent<RectTransform>(), new Vector2(0.51f, 0.06f), new Vector2(0.97f, 0.35f));
        InsetRect(bookContainer.GetComponent<RectTransform>(), 6f);
        bookContainer.AddComponent<Image>().color = new Color(1f, 1f, 1f, 0.07f);
        AddPanelOutline(bookContainer, new Color(1f, 1f, 1f, 0.32f));
        BuildSlotRow(bookContainer.transform, _bookSlots, "Skills Livro", "L");

        var catalogObj = CreateUiObject("Catalog", panel.transform);
        StretchRect(catalogObj.GetComponent<RectTransform>(), new Vector2(0.03f, 0.38f), new Vector2(0.58f, 0.94f));
        InsetRect(catalogObj.GetComponent<RectTransform>(), 6f);
        catalogObj.AddComponent<Image>().color = new Color(1f, 1f, 1f, 0.07f);
        AddPanelOutline(catalogObj, new Color(1f, 1f, 1f, 0.32f));
        CreateText(catalogObj.transform, "CatalogTitle", "Catalogo de Habilidades", new Vector2(0.04f, 0.88f), new Vector2(0.96f, 0.97f), 22f);

        var catalogGrid = CreateUiObject("CatalogContainer", catalogObj.transform);
        StretchRect(catalogGrid.GetComponent<RectTransform>(), new Vector2(0.04f, 0.04f), new Vector2(0.96f, 0.86f));
        var grid = catalogGrid.AddComponent<GridLayoutGroup>();
        grid.cellSize = new Vector2(120f, 120f);
        grid.spacing = new Vector2(8f, 8f);
        grid.constraint = GridLayoutGroup.Constraint.FixedColumnCount;
        grid.constraintCount = 5;
        _catalogContainer = catalogGrid.transform;
    }

    private void BuildSlotRow(Transform parent, List<SkillSlotUiRef> targetSlots, string title, string prefix)
    {
        CreateText(parent, $"{title}Title", title, new Vector2(0.03f, 0.80f), new Vector2(0.97f, 0.96f), 21f);
        const float gap = 0.018f;
        float slotW = (1f - gap * 5f) / 4f;
        for (int i = 0; i < 4; i++)
        {
            float minX = gap + i * (slotW + gap);
            float maxX = minX + slotW;
            var slotObj = CreateUiObject($"{prefix}Slot{i}", parent);
            StretchRect(slotObj.GetComponent<RectTransform>(), new Vector2(minX, 0.08f), new Vector2(maxX, 0.76f));

            var button = slotObj.AddComponent<Button>();
            var slotBg = slotObj.AddComponent<Image>();
            slotBg.color = new Color(1f, 1f, 1f, 0.12f);
            AddPanelOutline(slotObj, new Color(1f, 1f, 1f, 0.28f));
            var outlineObj = CreateUiObject("Selected", slotObj.transform);
            var outline = outlineObj.AddComponent<Image>();
            outline.color = new Color(1f, 0.85f, 0.2f, 0.5f);
            StretchRect(outlineObj.GetComponent<RectTransform>(), Vector2.zero, Vector2.one);
            outline.enabled = false;

            var visualStack = CreateUiObject("VisualStack", slotObj.transform);
            StretchRect(visualStack.GetComponent<RectTransform>(), new Vector2(0.48f, 0.12f), new Vector2(0.93f, 0.92f));
            var backgroundObj = CreateUiObject("BackgroundPaint", visualStack.transform);
            var background = backgroundObj.AddComponent<Image>();
            StretchRect(backgroundObj.GetComponent<RectTransform>(), Vector2.zero, Vector2.one);
            background.enabled = false;
            var frameObj = CreateUiObject("Frame", visualStack.transform);
            var frame = frameObj.AddComponent<Image>();
            StretchRect(frameObj.GetComponent<RectTransform>(), Vector2.zero, Vector2.one);
            frame.enabled = false;
            var iconObj = CreateUiObject("Icon", visualStack.transform);
            var icon = iconObj.AddComponent<Image>();
            StretchRect(iconObj.GetComponent<RectTransform>(), new Vector2(0.12f, 0.12f), new Vector2(0.88f, 0.88f));
            icon.enabled = false;

            var name = CreateText(slotObj.transform, "Name", "-", new Vector2(0.06f, 0.55f), new Vector2(0.44f, 0.92f), 16f, ellipsis: true);
            var cost = CreateText(slotObj.transform, "Cost", "0", new Vector2(0.06f, 0.1f), new Vector2(0.42f, 0.48f), 16f);

            targetSlots.Add(new SkillSlotUiRef
            {
                Button = button,
                BackgroundImage = background,
                FrameImage = frame,
                IconImage = icon,
                NameText = name,
                CostText = cost,
                SelectionOutline = outline
            });
        }
    }

    private void BuildDetails(Transform parent)
    {
        CreateText(parent, "NameLabel", "Nome", new Vector2(0.04f, 0.80f), new Vector2(0.96f, 0.87f), 13f);
        _detailNameText = CreateText(parent, "Name", "-", new Vector2(0.04f, 0.70f), new Vector2(0.96f, 0.79f), 22f, ellipsis: true);
        CreateText(parent, "DivinityLabel", "Divindade", new Vector2(0.04f, 0.62f), new Vector2(0.30f, 0.69f), 13f);
        _detailDivinityText = CreateText(parent, "Divinity", "-", new Vector2(0.32f, 0.62f), new Vector2(0.96f, 0.69f), 16f);

        CreateText(parent, "DescriptionLabel", "Descricao", new Vector2(0.04f, 0.54f), new Vector2(0.96f, 0.61f), 13f);
        _detailDescriptionText = CreateText(parent, "Description", "", new Vector2(0.04f, 0.30f), new Vector2(0.96f, 0.53f), 16f);
        if (_detailDescriptionText != null)
        {
            _detailDescriptionText.enableWordWrapping = true;
            _detailDescriptionText.overflowMode = TextOverflowModes.Ellipsis;
        }

        CreateText(parent, "PowerLabel", "Poder", new Vector2(0.04f, 0.22f), new Vector2(0.30f, 0.28f), 13f);
        _detailPowerText = CreateText(parent, "Power", "-", new Vector2(0.04f, 0.15f), new Vector2(0.30f, 0.21f), 16f);

        CreateText(parent, "CostLabel", "Custo", new Vector2(0.32f, 0.22f), new Vector2(0.58f, 0.28f), 13f);
        _detailCostText = CreateText(parent, "Cost", "-", new Vector2(0.32f, 0.15f), new Vector2(0.58f, 0.21f), 16f);

        CreateText(parent, "RangeLabel", "Alcance", new Vector2(0.60f, 0.22f), new Vector2(0.86f, 0.28f), 13f);
        _detailRangeText = CreateText(parent, "Range", "-", new Vector2(0.60f, 0.15f), new Vector2(0.86f, 0.21f), 16f);

        var detailVisual = CreateUiObject("DetailVisual", parent);
        StretchRect(detailVisual.GetComponent<RectTransform>(), new Vector2(0.68f, 0.04f), new Vector2(0.96f, 0.28f));
        var detailBgObj = CreateUiObject("BackgroundPaint", detailVisual.transform);
        _detailBackgroundImage = detailBgObj.AddComponent<Image>();
        StretchRect(detailBgObj.GetComponent<RectTransform>(), Vector2.zero, Vector2.one);
        _detailBackgroundImage.enabled = false;
        var detailFrameObj = CreateUiObject("Frame", detailVisual.transform);
        _detailFrameImage = detailFrameObj.AddComponent<Image>();
        StretchRect(detailFrameObj.GetComponent<RectTransform>(), Vector2.zero, Vector2.one);
        _detailFrameImage.enabled = false;
        var detailIconObj = CreateUiObject("Icon", detailVisual.transform);
        _detailIconImage = detailIconObj.AddComponent<Image>();
        StretchRect(detailIconObj.GetComponent<RectTransform>(), new Vector2(0.12f, 0.12f), new Vector2(0.88f, 0.88f));
        _detailIconImage.enabled = false;
    }

    private static GameObject CreateUiObject(string name, Transform parent)
    {
        var go = new GameObject(name, typeof(RectTransform));
        go.transform.SetParent(parent, false);
        return go;
    }

    private static void StretchRect(RectTransform rect, Vector2 min, Vector2 max)
    {
        rect.anchorMin = min;
        rect.anchorMax = max;
        rect.offsetMin = Vector2.zero;
        rect.offsetMax = Vector2.zero;
    }

    private static TMP_Text CreateText(Transform parent, string name, string text, Vector2 min, Vector2 max, float size, bool ellipsis = false)
    {
        var go = CreateUiObject(name, parent);
        var txt = go.AddComponent<TextMeshProUGUI>();
        txt.text = text;
        txt.fontSize = size;
        txt.color = Color.white;
        txt.alignment = TextAlignmentOptions.Left;
        if (ellipsis)
        {
            txt.enableWordWrapping = false;
            txt.overflowMode = TextOverflowModes.Ellipsis;
        }
        StretchRect(go.GetComponent<RectTransform>(), min, max);
        return txt;
    }

    private static Button CreateButton(Transform parent, string name, string text, Vector2 min, Vector2 max)
    {
        var go = CreateUiObject(name, parent);
        var image = go.AddComponent<Image>();
        image.color = new Color(1f, 1f, 1f, 0.16f);
        var button = go.AddComponent<Button>();
        var txt = CreateText(go.transform, "Text", text, Vector2.zero, Vector2.one, 20f);
        txt.alignment = TextAlignmentOptions.Center;
        StretchRect(go.GetComponent<RectTransform>(), min, max);
        return button;
    }

    private static void EnsureEventSystemExists()
    {
        if (FindObjectOfType<EventSystem>() != null) return;
        var eventSystem = new GameObject("EventSystem", typeof(EventSystem), typeof(StandaloneInputModule));
        DontDestroyOnLoad(eventSystem);
    }
}
